[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = {workspace = true}
tokio = {workspace = true}
tokio-util = {workspace = true}
futures = {workspace = true}
clap = {workspace = true}
utils = {workspace = true}